/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TBN9XV8b0Ip
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { DialogTitle, DialogHeader, DialogFooter, DialogContent, Dialog } from "@/components/ui/dialog"

export function Modal() {
  return (<>
    <Button>Open Modal</Button>
    <Dialog defaultOpen>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Email Address</DialogTitle>
        </DialogHeader>
        <div className="px-4 py-6 text-center">
          <p className="text-2xl font-medium">example@email.com</p>
        </div>
        <DialogFooter>
          <div>
            <Button variant="outline">Close</Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  </>);
}
